<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Andreas Regner</Authors>
    <RepositoryUrl>https://github.com/andireg/mockingbird</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Product>Mockingbird</Product>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
