<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Mockingbird</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Testing.Mockingbird</PackageId>
    <PackageTags>testing mocking net 10</PackageTags>
    <Description>
      This library should help you to test easily methods without writing all the mocks yourself.
      See - https://github.com/andireg/mockingbird
    </Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CodeDom" />
    <PackageReference Include="xunit.v3"  />
    <PackageReference Include="Moq"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mockingbird.Abstractions\Mockingbird.Abstractions.csproj" />
  </ItemGroup>

</Project>
